### ISSUE TITLE
remove redundant screen clearing

### ISSUE THREAD

**Issue by halvabner** [PaulJuliusMartinez/jless#124]
**To reproduce:** try using jless in urxvt

**Problem:** jless redundantly draws an empty screen and then redraws the entire new updated screen, even if it's just scrolling down.

This causes terminals that have a more frequent update rate like urxvt to make it unusable because it shows every time it clears and redraws.

**Comment by PaulJuliusMartinez** [comment]
The [latest version](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.9.0) of jless clears lines individually now, instead of clearing the entire screen. Can you try it out and let me know if that improves things?

Totally optimized screen rendering (only re-drawing the actual characters that have changed) is a significantly more work, so hopefully this is better.

**Comment by halvabner** [comment]
works like a charm, thanks ^_^. now it's my fav json viewer

**Comment by PaulJuliusMartinez** [comment]
Fantastic! And thanks for the report.
