### ISSUE TITLE
feature request: add keyboard shortcut to toggle expansion

### ISSUE THREAD

**Issue by aantn** [PaulJuliusMartinez/jless#41]
This is obviously a personal preference, but I strongly prefer using the same keyboard shortcut to both collapse and expand. It's much easier for me than splitting them into two separate shortcuts.

**Comment by PaulJuliusMartinez** [comment]
It's not documented, but right now `i` will toggle the focused node between expanded and collapsed.

That command might change though in a subsequent release. (I'm currently considering using `i`, representing "inspect", for printing out long string values, but haven't settled on anything yet.)

**Comment by aantn** [comment]
Cool, thanks

**Comment by aantn** [comment]
I know it's already taken but space seems like the obvious choice here and it's probably the first thing most people try. There are enough other ways you can scroll down one line that it seems wasted on that.

**Comment by PaulJuliusMartinez** [comment]
Good call on space, I went ahead and made the switch. I initially assigned it to move down because space in vim moves to the next character, but honestly I don't know anyone who uses that behavior. Similar with backspace, which in vim moves back a character, and in jless moves up (which feels weird).

I also tried out having space focus and collapse the parent node when on a primitive value rather than a container. It felt pretty good, but did seem a little inconsistent, since there was no way to perform the "focus and collapse parent" operation if all of a containers children were themselves containers. Maybe that functionality can be mapped to backspace.

**Comment by aantn** [comment]
Awesome thanks. It's a pity I just finished recording a video on jless with the old i key :)

I did warn it could change though.

https://youtu.be/mPSw9LdxKhg

Btw, happy to record another video on jless with anything you like. Also let me know if you have social media links (twitter etc) you'd like me to send people to
