### ISSUE TITLE
Copy full path of specific element(s) ?

### ISSUE THREAD

**Issue by reckoner** [PaulJuliusMartinez/jless#47]
After drilling down to a specific value, is it possible to copy the full path of that value? I can see it on the status line, but I can't see how you can extract the full path.

**Comment by avioli** [comment]
System Clipboard/Pasteboard support is **not** easy for *nix tools, that run in a shell although there is apparently a library for that ([clipboard](https://github.com/aweinstock314/rust-clipboard)) and might not be so tricky.

For now you'll be better off to manually select the status line path yourself (in [tmux copy mode](https://ianthehenry.com/posts/tmux-psa/) or with your mouse on many terminals).

**Comment by Gee19** [comment]
It might be a good starting point to print the path if jless was started with a certain flag like `jless --printpath` for example. It would also chain nicely with other unix tools and defer whatever action to perform on the result to the user. 

Now bear with me because I'm already excited about this project but this could theoretically replace plugins like [vim-jsonpath](https://github.com/mogelbrod/vim-jsonpath) and be a consistent experience in the shell too.

This would also open it up to printing language specific paths like `jless --printpath --lang='python'` which could be piped directly into an editor with some simple shell magic. Just an idea anyway, nice project and I look forward to using it.

**Comment by PaulJuliusMartinez** [comment]
Support for copying paths is now available in the [v0.8.0](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.8.0) release by using `yp`, `yb` or `yq`.

Full documentation is available by running `:help` inside `jless`, or in the [user guide](https://jless.io/user-guide.html#copying).
