### ISSUE TITLE
Scrolling doesn't respond correctly to window resizing

### ISSUE THREAD

**Issue by LovecraftianHorror** [PaulJuliusMartinez/jless#64]
## Steps to reproduce

1. Open a terminal
2. Pass some data to `jless`
    - Enough that more than the screen height is needed to display
3. Resize the height of the window
4. Scroll to the bottom to observe the active line go off-screen

## Info

- Reproduceable on current `main` (9ed0cbf1b702ba25107b6690c25e742c85e5cc10)
- `$ uname -a`: `Linux ai 5.16.11-arch1-2 #1 SMP PREEMPT Mon, 28 Feb 2022 10:17:30 +0000 x86_64 GNU/Linux`

Thanks for the great tool, and let me know if you want any more info! I use `i3-gaps` so resizing windows is pretty common (tiling WM and all)

**Comment by PaulJuliusMartinez** [comment]
Can you clarify how you're scrolling (holding down, `ctrl-e`, `ctrl-d`, `ctrl-f`, mouse scrolling, etc), whether you are increasing or decreasing the height of the window, what you mean by the active line going off the screen, and whether you're in data or line mode (you can press `m` to switch to line mode)? I haven't been to reproduce any issues. A video would be ideal.

It is intentional that you can scroll past the last line so that the last line is at the top of the screen and the rest of the screen just shows a `~` on each line.

Can you also verify that the window does at least respond to the resize and draws the bottom status bar in the correct location? (This is an issue in the v0.7.2 release: https://github.com/PaulJuliusMartinez/jless/issues/62, but should be fixed on main.)

Lastly, can you just verify that you _are_ actually running on the commit and not just the binary you installed elsewhere? (I constantly make this mistake.)

**Comment by LovecraftianHorror** [comment]
I can include a video and answer all those questions in about an hour or so!

**Comment by LovecraftianHorror** [comment]
> Lastly, can you just verify that you are actually running on the commit and not just the binary you installed elsewhere? (I constantly make this mistake.)

Woops. Looking back at my command history I built the executable, cd'd into `target/release`, annnd.. just ran the executable in my path still. I should have just piped the test data directly into `cargo run --release` from the get go.

Sorry for the false alarm. Everything seems to be working as intended!
