### ISSUE TITLE
Ctrl+Up/Down/Left/Right crashes the software

### ISSUE THREAD

**Issue by ztgasdf** [PaulJuliusMartinez/jless#65]
```
$ jless -V
jless 0.7.2
```
Prepending the command with `RUST_BACKTRACE=1`, I was able to acquire the following error message.

```
:thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Could not parse an event" }, src/app.rs:98:31
```

https://user-images.githubusercontent.com/83559531/157133082-01dbe889-4479-46bd-a544-10c04bc30aa6.mp4

**Comment by PaulJuliusMartinez** [comment]
This has been fixed in the [v0.8.0](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.8.0) release. The program no longer crashes, but it does print out an error. (The library used for parsing ANSI escape codes doesn't handle a fair number of multi-key inputs, also see https://github.com/PaulJuliusMartinez/jless/issues/61.)
