### ISSUE TITLE
How can I receive manual input instead of creating a JSON file separately

### ISSUE THREAD

**Issue by hjldev** [PaulJuliusMartinez/jless#83]
when i enter:   jless {"test": "test"}
tips:   zsh: parse error near `}

**Comment by leoperegrino** [comment]
Zsh is trying to interpret the curly braces before any type of parsing from jless. You need to quote strings containing curly braces, if shell brace expansion is not your goal. But even then, in this case, jless does not handle arguments as input for parsing, just as filenames to open, check `jless --help`. 

What you can do in this situation is pipe the test string to jless, with proper quotation to prevent the shell to misinterpret. That is:
`echo '{"test": "test"}' | jless`

**Comment by PaulJuliusMartinez** [comment]
As noted, you need to quote your JSON so it's interpreted as a string rather than parsed by your shell, and you need to pipe the input to jless rather than providing JSON as the actual argument.

 Semi-related, [`jo`](https://github.com/jpmens/jo) is a tool that can be used to build JSON objects from the command line.
